package service2;

import main.ServiceCaller;
import service2.types.Service2Call1Input;
import service2.types.Service2Call1Output;
import service2.types.Service2Call2Input;
import service2.types.Service2Call2Output;

// This code is automatically generated by Guidewire from Service2Itf
public class Service2CodeGen implements Service2Itf {
  @Override
  public Service2Call1Output call1(Service2Call1Input input) throws Exception {
    return new ServiceCaller<Service2Call1Input, Service2Call1Output>().invoke(Service2Itf.class, "call1", input);
  }

  @Override
  public Service2Call2Output call2(Service2Call2Input input) throws Exception {
    return new ServiceCaller<Service2Call2Input, Service2Call2Output>().invoke(Service2Itf.class, "call2", input);
  }
}
